### ISSUE TITLE
Fix issue setting up liquid simulations of mixed solutes/solvents (binary mixtures or higher order)

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/openmoltools#103] opened 2015-05-01 01:01 UTC
There's currently a small hiccup where the residue names need to be massaged to work properly.

**Comment by davidlmobley** [comment] 2015-05-01 15:48
To explain the issue to other onlookers, I tried to adapt @kyleabeauchamp's pure liquid benchmark code (https://github.com/choderalab/LiquidBenchmark/blob/master/src/simulation/liquid_tools.py) to handle some mixed solutions which I need to set up (at this point binary mixtures, though my code would effectively be the same for ternary or higher order mixtures, or for an arbitrary solute in a pure solvent), and ran into a snag - the pipeline fails with an error:

raise(ValueError("Must have UNIQUE residue names in each mol2 file."))
in build_mixture_prmtop

On investigation it turns out the issue is that `openmoltools.openeye.smiles_to_antechamber` by default assigns a residue name of `MOL`, whereas `openmoltools.amber.build_mixture_prmtop` requires unique residue names. So in ANY case where a user specifies multiple solutes/solvents with default residue names, this will fail. 

The issue could be worked-around by the user providing an appropriate residue name for each solute/solvent considered, though in general that will probably be a pain.

A general solution seems to be fairly nontrivial. If every molecule has to have a unique residue name (which I assume it does) AND this has to be a three-character alphabetic/alphanumeric sequence (which I'm assuming it does for PDB format reasons... And I believe this needs to be uppercase or is not case sensitive) then there's only 17k-46k (26^3-36^3) possible residue names, which is not enough to cover "all of chemical space". So there's no way we can assign a truly unique residue name to each molecule we might want to consider.

I'm thinking that the best solution is to (by default) assign each molecule a random alphabetic residue name (excluding standard amino acid and nucleic acid names, I suppose; anything else to exclude?) and then just have the build_mixture_prmtop check that these are unique (to avoid the off-chance that we accidentally get two which match) and (by default) rename one residue if they do.

This is high priority for me, so I'll get to work implementing this unless there are immediate objections or suggestions of a better way to handle things.

**Comment by kyleabeauchamp** [comment] 2015-05-01 15:49
I may have a partial solution here: https://github.com/choderalab/openmoltools/pull/104/

**Comment by davidlmobley** [comment] 2015-05-01 21:20
Fixed by #104

**Closed by davidlmobley** 2015-05-01 21:20 UTC
Labels: bug
